// Estado mutable compartido. Firebase y la UI siguen siendo las fuentes de estado
// de la partida; este objeto solamente conserva el estado local del cliente.
export const state = {
  mode:null, gameType:'whoami', roomCode:'', playerId:'', playerName:'', hostName:'',
  categories:[], totalRounds:3, roomRef:null, roomListener:null, serverTimeOffset:0,
  myAssignment:null, countdownTimer:null, countdownWatchdogTimer:null, countdownKey:'', countdownPhase:'', countdownEndAt:0, countdownPerformanceEndAt:0, countdownTransitioningKey:'', transitionKey:'', configEditing:false,
  wakeLock:null, countdownFeedbackKey:'', soundUnlocked:false,
  busy:{create:false,join:false,start:false,score:false,confirm:false,next:false,restart:false,reconnect:false,finishGame:false,leave:false},
  restoring:false,autoRestoring:false,authReady:false,authUser:null,anonymousSignInStarted:false,registeringAccount:false,authEventToken:0,profile:null,accountListenerUid:'',lastRoomData:null,currentScreen:'',scoringRenderKey:'',privateAssignment:null,privateAssignmentRef:null,privateAssignmentListener:null,miniPrivateAssignmentRef:null,miniPrivateAssignmentListener:null,miniPrivateAssignment:null,tribunalPrivateAssignment:null,chamuyayaPrivateAssignment:null,friendData:{},friendProfiles:{},friendPresence:{},requestData:{},inviteData:{},friendPresenceRefs:{},friendProfileRefs:{},profileListener:null,friendListener:null,requestListener:null,inviteListener:null,accountPresenceRef:null,presenceOnline:false,searchTarget:null,pendingInviteRoom:'',lastConnected:null,connectionWatchdog:null,reconnectModalOpen:false,roomConnectionPaused:false,privateAssignmentRecoveryTimer:null,privateAssignmentRecoveryAttempts:0,requestListenerInitialized:false,lastRequestKeys:new Set(),guestMode:false,quickFriendsOpen:false,friendsLoaded:false,splashDone:false,hostTransferAttemptKey:'',pendingRoundToken:'',pendingAssignments:null,assignmentRetryToken:'',assignmentRetryCount:0,assignmentRetryAt:0,roundWriteInProgress:false,assignmentRecoveryInProgress:false,reconnectMaxAttempts:6,transitionRetryTimer:null,roomHeartbeatTimer:null,miniCountdownTimer:null,miniCountdownWatchdog:null,miniCountdownKey:'',miniCountdownTick:null,miniCountdownTransitioningKey:'',miniRenderKey:'',stopFormToken:'',miniConfig:null,ageLocalEstimate:'',ageEstimateRoundToken:'',ageSubmitInFlight:false,confessionSubmitInFlight:false,confessionVoteInFlight:false,stopDrafts:{},stopDraftTimer:null,chupistica:null,chupisticaTimers:[],stopConfig:null,chamuyayaLocal:null
};
